version: '3'
services:
  devenv:
    build: .
    volumes:
    - .:/code
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    working_dir: /code
