<?xml version="1.0"?>
<robot name="parameters" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="scale" value="1.2" />
  <xacro:property name="p1_len" value="${scale*0.203200}" />  <!-- in meters -->
  <xacro:property name="p2_len" value="${scale*0.241300}" />
  <xacro:property name="p3_len" value="${scale*0.101600}" />
  <xacro:property name="p4_len" value="${scale*0.088900}" />
  <xacro:property name="p5_len" value="${scale*0.152400}" />
  <xacro:property name="p6_len" value="${scale*0.146050}" />
  <xacro:property name="p7_len" value="${scale*0.285750}" />
  <xacro:property name="p8_len" value="${scale*0.038100}" />
  <xacro:property name="p9_len" value="${scale*0.038100}" />
  <xacro:property name="c_offset" value="0.0127" />
  <xacro:property name="wheel_radius" value="0.07" />
  <xacro:property name="front_wheels_offset" value="${[0, 0.04]}" />
  <xacro:property name="rear_wheels_offset" value="${[0, 0.04]}" />
  <xacro:property name="base_level" value="0.19" />
  <xacro:property name="back_angle_deg" value="20" />
  <xacro:property name="rest_angle_deg" value="48.8" />
  <xacro:property name="lock_angle_deg" value="20.5" />
  <!-- Derivative Quantities -->
  <xacro:property name="p1_hlen" value="${p1_len/2}" />
  <xacro:property name="p2_hlen" value="${p2_len/2}" />
  <xacro:property name="p3_hlen" value="${p3_len/2}" />
  <xacro:property name="p4_hlen" value="${p4_len/2}" />
  <xacro:property name="p5_hlen" value="${p5_len/2}" />
  <xacro:property name="p6_hlen" value="${p6_len/2}" />
  <xacro:property name="p7_hlen" value="${p7_len/2}" />
  <xacro:property name="p8_hlen" value="${p8_len/2}" />
  <xacro:property name="p9_hlen" value="${p9_len/2}" />
  <xacro:property name="back_angle_rad" value="${radians(back_angle_deg)}" />
  <xacro:property name="rest_angle_rad" value="${radians(rest_angle_deg)}" />
  <xacro:property name="lock_angle_rad" value="${radians(lock_angle_deg)}" />
</robot>
