<?xml version="1.0"?>
<robot name="parameters" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="p1_len" value="0.203200" />  <!-- in meters -->
  <xacro:property name="p2_len" value="0.241300" />
  <xacro:property name="p3_len" value="0.101600" />
  <xacro:property name="p4_len" value="0.088900" />
  <xacro:property name="p5_len" value="0.152400" />
  <xacro:property name="p6_len" value="0.146050" />
  <xacro:property name="p7_len" value="0.285750" />
  <xacro:property name="p8_len" value="0.038100" />
  <xacro:property name="p9_len" value="0.038100" />
  <xacro:property name="c_offset" value="0.0127" />
  <xacro:property name="gearbox_plate_offset" value="0.01" />
  <xacro:property name="wheel_radius" value="0.0762" />
  <xacro:property name="caster_radius" value="0.0508" />
  <xacro:property name="swivel_offset" value="0.02" />
  <xacro:property name="base_level" value="0.12" />
  <xacro:property name="back_angle_deg" value="20" />
  <xacro:property name="rest_angle_deg" value="48.8" />
  <xacro:property name="lock_angle_deg" value="20.5" />
  <!-- Derivative Quantities -->  
  <xacro:property name="p1_hlen" value="${p1_len/2}" />
  <xacro:property name="p2_hlen" value="${p2_len/2}" />
  <xacro:property name="p3_hlen" value="${p3_len/2}" />
  <xacro:property name="p4_hlen" value="${p4_len/2}" />
  <xacro:property name="p5_hlen" value="${p5_len/2}" />
  <xacro:property name="p6_hlen" value="${p6_len/2}" />
  <xacro:property name="p7_hlen" value="${p7_len/2}" />
  <xacro:property name="p8_hlen" value="${p8_len/2}" />
  <xacro:property name="p9_hlen" value="${p9_len/2}" />
  <xacro:property name="back_angle_rad" value="${back_angle_deg*pi/180}" />
  <xacro:property name="rest_angle_rad" value="${rest_angle_deg*pi/180}" />
  <xacro:property name="lock_angle_rad" value="${lock_angle_deg*pi/180}" />
</robot>
