<?xml version="1.0"?>
<robot name="motion" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find pvcchair_description)/urdf/includes/parameters.xacro" />
  <xacro:include filename="$(find pvcchair_description)/urdf/includes/parts/caster.xacro" />
  <xacro:include filename="$(find pvcchair_description)/urdf/includes/parts/gearbox_plate.xacro" />
  <xacro:include filename="$(find pvcchair_description)/urdf/includes/parts/wheel.xacro" />

  <xacro:macro name="drive" params="parent">
    <xacro:gearbox_plate
      suffix="right"
      parent="${parent}"
      xyz="${p1_hlen+c_offset+gearbox_plate_offset} ${-p2_hlen-c_offset-0.015} ${gearbox_plate_offset}" />
    <xacro:gearbox_plate
      suffix="left"
      parent="${parent}"
      xyz="${p1_hlen+c_offset+gearbox_plate_offset} ${+p2_hlen+c_offset+0.015} ${gearbox_plate_offset}" />

    <xacro:wheel
      suffix="right"
      parent="gearbox_plate_right_link"
      xyz="-0.052 -0.02 -0.054" />
    <xacro:wheel
      suffix="left"
      parent="gearbox_plate_left_link"
      xyz="-0.052 +0.02 -0.054" />

    <xacro:caster
      suffix="right"
      parent="${parent}"
      xyz="${-p1_hlen-2*c_offset-p3_len-c_offset+swivel_offset} ${-p2_hlen-c_offset} ${c_offset+p9_len}" />
    <xacro:caster
      suffix="left"
      parent="${parent}"
      xyz="${-p1_hlen-2*c_offset-p3_len-c_offset+swivel_offset} ${+p2_hlen+c_offset} ${c_offset+p9_len}" />
  </xacro:macro>

</robot>
