<?xml version="1.0"?>
<robot name="swerve_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find pvcchair_description)/urdf/includes/parameters.xacro" />

  <xacro:macro name="swerve_wheel" params="prefix parent x y yaw:=0">
    <xacro:property name="box_size" value="0.05" />
    <xacro:property name="wheel_width" value="0.0254" />
    <xacro:property name="wheel_base_clearance" value="0.005" />

    <link name="${prefix}_wheel_base_link">
      <inertial>
        <mass value="0.2" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.000333" ixy="0.000000" ixz="0.000000"
                                iyy="0.000333" iyz="0.000000"
                                               izz="0.000333" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${box_size} ${box_size} ${box_size}" />
        </geometry>
        <material name="gray">
          <color rgba="0.8 0.8 0.8 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${box_size} ${box_size} ${box_size}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_wheel_base_joint" type="fixed">
      <origin xyz="${x} ${y} ${-base_level+2*wheel_radius+wheel_base_clearance+box_size/2}" rpy="0 0 ${yaw}" />
      <parent link="${parent}" />
      <child link="${prefix}_wheel_base_link" />
    </joint>

    <link name="${prefix}_caster_rotation_link">
      <inertial>
        <mass value="0.2" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.000333" ixy="0.000000" ixz="0.000000"
                                iyy="0.000333" iyz="0.000000"
                                               izz="0.000333" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${-box_size/4+wheel_radius/2+wheel_base_clearance/2}" rpy="0 0 0" />
        <geometry>
          <box size="${box_size} ${box_size} ${box_size/2+wheel_radius+wheel_base_clearance}" />
        </geometry>
        <material name="dark_gray">
          <color rgba="0.6 0.6 0.6 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${-box_size/4+wheel_radius/2+wheel_base_clearance/2}" rpy="0 0 0" />
        <geometry>
          <box size="${box_size} ${box_size} ${box_size/2+wheel_radius+wheel_base_clearance}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_caster_rotation_joint" type="continuous">
      <axis xyz="0 0 1" />
      <origin xyz="0 0 ${-box_size/2-wheel_radius-wheel_base_clearance}" rpy="0 0 0" />
      <parent link="${prefix}_wheel_base_link" />
      <child link="${prefix}_caster_rotation_link" />
    </joint>

    <link name="${prefix}_caster_r_wheel_link">
      <inertial>
        <mass value="0.2" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.000300" ixy="0.000000" ixz="0.000000"
                                iyy="0.000300" iyz="0.000000"
                                               izz="0.000580" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_caster_r_wheel_joint" type="continuous">
      <axis xyz="0 ${copysign(1,y)} 0" />
      <origin xyz="0 ${box_size/2+wheel_width/2+0.005} 0" rpy="0 0 0" />
      <parent link="${prefix}_caster_rotation_link" />
      <child link="${prefix}_caster_r_wheel_link" />
    </joint>
  </xacro:macro>

</robot>
